### ISSUE TITLE
uncaught error in data.svelte promise

### ISSUE THREAD

**Issue by whysthatso** [osarrouy/robinhoodcoop#28] opened 2020-09-07 12:56 UTC
url: https://member.robinhoodcoop.org/

```
Data.svelte:42 Uncaught (in promise) TypeError: Cannot read property 'timestamp' of null
    at Object.next (Data.svelte:42)
    at g (Observable.js:135)
    at b (Observable.js:179)
    at e.value (Observable.js:235)
    at Object.next (Observable.js:327)
    at g (Observable.js:135)
    at b (Observable.js:179)
    at e.value (Observable.js:235)
    at bundle.esm.js:866
    at Set.forEach (<anonymous>)
```

**Comment by osarrouy** [comment] 2020-10-09 10:57
I can't reproduce the issue. This was probably because the GraphQL query could not load the time at which the share value was last updated - because it was not yet. The problem must be solved now that the value has been set.

Closing for now.

**Closed as completed by osarrouy** 2020-10-09 10:57 UTC
